#!/bin/bash

usage() {
	while read; do printf '%s\n' "$REPLY"; done <<- EOF
		Usage: lock-[flags]
		    Flags:
		        --help|-h                       Show this message.
		        --image_file|-w                 Lock screen with wallpaper.
		        --screenshot|-s                 Lock screen with a screenshot of your current workspace.

		        --grayscale|-g                  Make the image grayscale.
		        --pixelize|-p                   Pixelize the image.
		        --blur|-b                       Blur the image.
	EOF
}

# taking screen shot and saving it to temp
scrot /tmp/screen.png

# bluring the screen shot
convert /tmp/screen.png -blur 0x8 /tmp/screen.png

# pixlate
#convert /tmp/screen.png -scale 10% -scale 1000% /tmp/screen.png

#convert to B/W
#convert -type Grayscale /tmp/screen.png /tmp/screen.png

# merging fossaia logo with image
composite -blend 9 lock-head.png -gravity center /tmp/screen.png /tmp/screen.png

#use i3lock
i3lock -u -i /tmp/screen.png

# clean temp
rm /tmp/screen.png
