#!/bin/bash

# taking screen shot and saving it to temp
scrot /tmp/screen.png

# bluring the screen shot
convert /tmp/screen.png -blur 0x8 /tmp/screen.png

# pixlate
#convert /tmp/screen.png -scale 10% -scale 1000% /tmp/screen.png

#convert to B/W
#convert -type Grayscale /tmp/screen.png /tmp/screen.png

# merging fossaia logo with image
composite -blend 9 lock-head.png -gravity center /tmp/screen.png /tmp/screen.png

#use i3lock
i3lock -u -i /tmp/screen.png

# clean temp
rm /tmp/screen.png
